### ISSUE TITLE
Amélioration de l'intégration continue

### ISSUE THREAD

**Issue by Lollipoke** [dil-classroom/projet-egger_gehring_schaller_vogel#21]
En tant que développeur, j’aimerais que les pull requests ne puissent être mergées que lorsque la compilation et les
tests ne produisent pas d’erreur. De plus, il ne devrait pas être possible de merger une pull request lorsque le code
est mal formaté

**Comment by jorisSchaller** [comment]
l'intégration continue a été mise en place lors de #42
