### ISSUE TITLE
Traduire les différents contenus en français

### ISSUE THREAD

**Issue by jorisSchaller** [dil-classroom/projet-egger_gehring_schaller_vogel#25]
- optimiste 1h
 - pessimiste 3h
 - attendu1h
close #25  
Edit: traduction en français

**Comment by vogelma** [comment]
Réalisé en 45min.
Les issues ont été traduites même celle fermées.
Une pull request a été faite pour la version en français du code de conduite.

**Comment by jorisSchaller** [comment]
la pr a été merge, je ferme cette issue
